= Introduction

|===
|Last update of text: |`2025-09-15 (v0.1.0)`
|Last update of screenshots: |`-`
|===

== What is Jam Pad?

link:https://www.helgoboss.org/projects/jampad[Jam Pad] is a versatile app for managing recordings and musical ideas. It is designed as a valuable tool for everyone who deals with audio recordings: Musicians, composers, ensembles, bands, sound artists, music teachers, podcasters, podcast listeners and music studios.


Jam Pad keeps xref:key-concepts.adoc#recording[audio recordings] and additional data such as xref:key-concepts.adoc#marker[markers], xref:key-concepts.adoc#playlist[playlists] and xref:key-concepts.adoc#sheet[sheets] organized in so-called xref:key-concepts.adoc#space[spaces].

It works completely offline but also offers optional device-to-device synchronization and cloud collaboration features.

From the technical side, it's a native app which runs on the following platforms:

- Android phones and tablets
- iOS phones and tablets
- macOS computers
- Windows computers

Support for the following platforms is planned:

- Linux computers
- Browsers (very restricted feature set)

== Special qualities

Jam Pad is engineered from the ground up to unite a set of qualities rarely seen in one place.

=== Offline-first

Most of Jam Pad's features work completely without internet access. This is not just an  indispensable feature for train rides or walks in the forest in countries with bad network coverage {empty}footnote:[Greetings from Germany!], it also makes Jam Pad generally very fast and snappy to use.

Even collaborative features are usable offline and only require internet access for synchronization.

=== Privacy-first

Each xref:key-concepts.adoc#space[space] starts as a xref:key-concepts.adoc#single-device-space[single-device space]. That means its data is stored on your device only and will not be synced anywhere else (cloud or other devices) unless you explicitly want that.

xref:key-concepts.adoc#multi-device-space[Multi-device spaces] allow you to synchronize your data directly between multiple devices, without sacrificing privacy.

Finally, xref:key-concepts.adoc#cloud-space[Cloud spaces] enable collaborative features. For this, it is technically necessary to save your data on servers. Our server is protected by state-of-the art security measures and hosted in Europe.

For music studios (and interested users) who don't want to put their data in anyone else's hands, we plan to offer the opportunity to purchase a server license, which makes it possible to host the Jam Pad server engine yourself. This allows you to keep all data - including the user identity management - on your own machines, for example a NAS.

[NOTE]
====
Please contact info@helgoboss.org if you are interested in self-hosting!
====

=== No account necessary

A xref:key-concepts.adoc#account[Jam Pad account] is only required if you want to create or join a xref:key-concepts.adoc#cloud-space[] (to unlock Jam Pad's collaborative features) or if you want to sync xref:key-concepts.adoc#in-app-purchase[in-app purchases] across multiple platforms.

=== Cross-platform

Jam Pad is available for Android, iOS, macOS and Windows with most features available on all of those platforms. Synchronization of spaces between any of those platforms works seamlessly.

=== Open data

Jam Pad is not a one-way street for your data. You can xref:space-export-import.adoc[export] a space including all of its recordings and metadata at any time. The export format is xref:space-export-import.adoc[well documented]. Want to migrate everything to another system at some point? No problem.

Vice versa, it's possible to xref:space-export-import.adoc[import] data again. If you have existing data that you want to migrate to Jam Pad, that's only a matter of building a file that corresponds to the export format and importing it into the app.

=== Data safety

Jam Pad allows you to create backups manually that you can restore whenever necessary.

If you use xref:key-concepts.adoc#cloud-space[multi-device spaces] or xref:key-concepts.adoc#cloud-space[cloud spaces], your space will automatically end up on multiple machines, providing an additional safety layer.

=== Thoughtful internals

There are many apps out there which look attractive but fall short when it comes to carrying our operations under the hood. Jam Pad is not one of them!

As an example, the way Jam Pad lays out its data on your local device storage is very logical - one space corresponds to one folder. Within that space folder, core data is strictly separated from user-/device-specific data. That makes it possible to pass one space 1:1 to another Jam Pad installation just by copying a directory without the user- or device -specific data. This data layout also makes automated file-system-based backups a breeze.

=== Versatile and scalable

In stark contrast to other offers out there, Jam Pad is not just about collaboration. It starts being a useful tool much sooner, before things end up in collaboration. You can benefit from it even as a solo musician. Later you can use the same tool that you love for doing collaboration in bands or studios, so everything feels natural. It has a wide range of xref:usage-scenarios.adoc[]. Jam Pad grows with your needs!

=== Fair pricing

Lots of great features are available for free. Many advanced features are purchasable for lifetime usage, without running fees. Only features which require regular maintenance and costs on our side require a paid subscription.