= Key concepts

[[space]]
== Space

Spaces are the top-level organizational unit of Jam Pad. A space is a self-contained collection of <<clip,clips>>, <<marker,markers>>, <<playlist,playlists>>, <<sheet,sheets>>, <<comment,comments>> and - in collaborative spaces also - <<message, messages>>.

Musicians will typically create at least one space for themselves and then one for each band / musical project. Studios will typically create one space for each client or album.

[[single-device-space]]
=== Single-device space

All clips and other data in a single-device space stay on your device and your device only. You can create as many single-device spaces as you want.

Each space starts as single-device space and can later be upgraded to a <<multi-device-space>> or <<cloud-space>>.

[[multi-device-space]]
=== Multi-device space

A multi-device space is a space that is synchronized between multiple devices directly, so that you can conveniently access it from all of them, for example from your mobile phone and your computer.

For this to work, you first need to configure one Jam Pad installation to act as <<main-device>> and then pair it with one or more <<companion-device, companion devices>>. For example, a computer makes a good main device and a mobile phone a good companion. After this one-time setup, you can upgrade arbitrary <<single-device-space,single-device spaces>> to multi-device spaces.

Small data (such as markers) of a multi-device space will be seamlessly synced bidirectionally between your paired devices, so that you can access it even after connection between the devices is lost. Large data (such as clips) will always be synced to the <<main-device>>, so that it eventually always gets all of your clips. <<companion-device,Companion devices>> can selectively download clips from the main device because companion devices typically have limited storage.

The connection happens over your local Wi-Fi network and optionally even over the internet. In both cases, it's an end-to-end-encrypted peer-to-peer connection. Perfect for privacy!

TIP: When synchronizing over the internet, so-called link:https://en.wikipedia.org/wiki/Relay_network[relay servers] might help to establish the initial connection between the devices, but even then, no servers will be able to read your data.

NOTE: Multi-device synchronization is a paid feature.

[[cloud-space]]
=== Cloud space

A cloud space is a private space that lives in the internet and can be synchronized from and to arbitrary devices, so that you and invited space members (and nobody else!) can conveniently access it from everywhere.

For this to work, you first need to create a <<account, Jam Pad account>> and log in. After this one-time setup, you can upgrade arbitrary <<single-device-space,single-device spaces>> to cloud spaces.

All data of a cloud space will automatically be synchronized to the cloud and is by default **only** accessible from your account. You can log into the same account on your other devices and will automatically see the space there and work with it.

Small data (such as markers) will be seamlessly synced bidirectionally between your device and the cloud, so that you can access it even after you go offline. Large data (such as clips) will always be synced to the cloud. You can selectively download clips from the cloud to make them available offline as well.

Cloud spaces come with additional collaborative features! You can invite other Jam Pad users to participate in your space, for example the members of your band or a client. They will see more or less the same clips and data and can contribute by uploading own clips, adding playlists, commenting, marking, creating or changing <<sheet,sheets>>. It's also possible to send <<message,messages>> to your team, for example to start talking about certain musical passages or improvements.

[NOTE]
====
Creating and maintaining cloud spaces requires a paid subscription.
But: Invited space members can join without subscription ❤️

Depending on your selected cloud plan, limits apply:

* Maximum number of participating users (across all of your own cloud spaces)
* Maximum storage space (across all of your own cloud spaces)
* Maximum number of owned cloud spaces
====

[[space-objects]]
== Space objects

[[clip]]
=== Clip

Simply spoken, clips are audio files.

TODO

[[clip-id]]
==== Clip ID

TODO

[[clip-version]]
==== Clip version

[[asset]]
=== Asset

In Jam Pad, an asset is a larger file, such as an audio file (representing a clip version or an audio marker) or a waveform peak file.

[[asset-id]]
==== Asset ID

Every asset in Jam Pad has a unique identifier. Most of the time you won’t need to think about it, but if you explore the app more deeply, it’s useful to know what it represents.

An asset ID is an uppercase, 26-character string that looks cryptic at first glance. It’s actually a checksum of the asset’s content. This means that two assets with identical content will always produce the same ID. As a result, Jam Pad automatically avoids duplicates within a space, helping you save storage.




[[marker]]
=== Marker

TODO

[[playlist]]
=== Playlist

TODO

[[sheet]]
=== Sheet

TODO

[[comment]]
=== Comment

TODO

[[message]]
=== Message

TODO

=== Custom metadata

TODO

[[custom-field]]
==== Custom property

TODO

[[custom-item-type]]
==== Custom item type

TODO

[[custom-item]]
==== Custom item

TODO


== Other space-related things

[[space-export]]
=== Space export

TODO


== Device-to-device synchronization

TODO

[[main-device]]
=== Main device

TODO

[[companion-device]]
=== Companion device

TODO

== Cloud synchronization

TODO

[[account]]
=== Account

TODO

== App

[[in-app-purchase]]
=== In-app purchase

TODO

