= Space export/import

Jam Pad allows you to export a space including all of its clips and other data to a folder of your choice. The reverse, importing from a folder, is also possible.

== Export format

=== Folder structure

A space export is a folder with the following structure:

[source,text]
.Example
----
hello/
├── assets/                             <1>
│   ├── YSBSZJJZCGD68JDB969J4SDFAC.m4a  <2>
│   ├── RS48WGQ5FZE6EZ7V1S16NJXFEW.mp3
├── hello.space.jampad.json             <3>
----

<1> The folder containing all space xref:key-concepts.adoc#asset[assets]
<2> The actual assets, for example, clip media files
<3> A link:https://www.json.org/json-en.html[JSON] file that contains a snapshot of all the other data in this space (markers, playlists, sheets, ...)

=== The JSON file

link:https://www.json.org/json-en.html[JSON] is a widely used data exchange format. Unlike CSV, it can easily represent nested structures, which is important because Jam Pad spaces can get quite complex.

Let's look at an example:

[%collapsible]
.Example JSON file
====
[source,json]
----
include::example$nature-and-music-20250916-100619.space.jampad.json[]
----
====



== Export/import vs. Backup/restore


