= Space export/import

Jam Pad allows you to export a space including all of its clips and other data to a folder of your choice. The reverse, importing from a folder, is also possible.

== Export format

[TIP]
====
You don't need to understand anything in this section if you simply want to export or import spaces!

This section is intended for ...

- ... power users who want to modify their spaces in a text editor.
- ... developers who want to build an import/export function for their own software.
====

=== Folder structure

A space export is a folder with the following structure:

[source,text]
.Example
----
hello/
├── assets/                             <1>
│   ├── YSBSZJJZCGD68JDB969J4SDFAC.m4a  <2>
│   ├── RS48WGQ5FZE6EZ7V1S16NJXFEW.mp3
├── hello.space.jampad.json             <3>
----

<1> The folder containing all space xref:key-concepts.adoc#asset[assets]
<2> The actual assets, for example, clip media files
<3> A link:https://www.json.org/json-en.html[JSON] file that contains a snapshot of all the other data in this space (markers, playlists, sheets, ...)

=== The JSON file

link:https://www.json.org/json-en.html[JSON] is a widely used data exchange format. Unlike CSV, it can easily represent nested structures, which is important because Jam Pad spaces can get quite complex.

Let's look at an example:

[%collapsible]
.Example space export file
====
[source,json]
----
include::example$nature-and-music-20250916-100619.space.jampad.json[]
----
====

The structure of space export files is specified in link:https://json-schema.app/view/%23?url=https%3A%2F%2Fraw.githubusercontent.com%2Fhelgoboss%2Fjampad-public%2Frefs%2Fheads%2Fmain%2Fdocs%2Fantora%2Fmodules%2FROOT%2Fattachments%2Fspace.jampad.schema.json[this JSON Schema file]. JSON schema files are made for machines, so they are not very readable. However, you can use a JSON Schema Viewer to read it like a specification:

link:https://json-schema.app/view/%23?url=https%3A%2F%2Fraw.githubusercontent.com%2Fhelgoboss%2Fjampad-public%2Frefs%2Fheads%2Fmain%2Fdocs%2Fantora%2Fmodules%2FROOT%2Fattachments%2Fspace.jampad.schema.json[Inspect Jam Pad space export schema in JSON Schema Viewer!]



== Export/import vs. Backup/restore


